## document:
## 	see also: https://docs.brew.sh/Formula-Cookbook
require "formula"
class dotfiles < Formula

  # esample: Basic instructions
  ##
  ## class Foo < Formula
  ##   desc ""
  ##   homepage ""
  ##   url "https://example.com/foo-0.1.tar.gz"
  ##   sha256 "85cc828a96735bdafcf29eb6291ca91bac846579bcef7308536e0c875d6c81d7"
  ##   license ""
  ## 
  ##   # depends_on "cmake" => :build
  ## 
  ##   def install
  ##     # ENV.deparallelize
  ##     system "./configure", "--disable-debug",
  ##                           "--disable-dependency-tracking",
  ##                           "--disable-silent-rules",
  ##                           "--prefix=#{prefix}"
  ##     # system "cmake", ".", *std_cmake_args
  ##     system "make", "install"
  ##   end
  ## 
  ##   test do
  ##     system "false"
  ##   end
  ## end
  homepage "https://github.com/UmedaTakefumi/dotfiles"
  url "https://github.com/UmedaTakefumi/dotfiles/archive/refs/tags/0.01.zip"
  sha256 "1cd4a14b75ef9b6cb0dc7ca5d77e988da8731733c0dfa0bdf15b5c0babefdda8"
  head "https://github.com/UmedaTakefumi/dotfiles.git"
  version "0.01"

  # example: Specifying other formulae as dependencies
  ## 
  ## depends_on "pkg-config"
  ## depends_on "jpeg"
  ## depends_on "readline" => :recommended
  ## depends_on "gtk+" => :optional
  ## depends_on "httpd" => [:build, :test]
  ## depends_on :xcode => "9.3"
  depends_on "ansible"
  depends_on "autoconf"
  depends_on "automake"
  depends_on "awscli"
  depends_on "bdw-gc"
  depends_on "berkeley-db"
  depends_on "c-ares"
  depends_on "ca-certificates"
  depends_on "cairo"
  depends_on "cdrtools"
  depends_on "cmake"
  depends_on "cocoapods"
  depends_on "dart"
  depends_on "dnsmasq"
  depends_on "docker-compose"
  depends_on "docker-machine"
  depends_on "exiftool"
  depends_on "fontconfig"
  depends_on "freetype"
  depends_on "gcc"
  depends_on "gdb"
  depends_on "gdbm"
  depends_on "gettext"
  depends_on "ghq"
  depends_on "glib"
  depends_on "gmp"
  depends_on "gnutls"
  depends_on "go"
  depends_on "guile"
  depends_on "hugo"
  depends_on "hyperkit"
  depends_on "isl"
  depends_on "jemalloc"
  depends_on "jigdo"
  depends_on "jpeg"
  depends_on "kubernetes-cli"
  depends_on "libev"
  depends_on "libevent"
  depends_on "libffi"
  depends_on "libgcrypt"
  depends_on "libgpg-error"
  depends_on "libidn2"
  depends_on "libmaxminddb"
  depends_on "libmpc"
  depends_on "libnghttp2"
  depends_on "libpng"
  depends_on "libpthread-stubs"
  depends_on "libslirp"
  depends_on "libsmi"
  depends_on "libssh"
  depends_on "libssh2"
  depends_on "libtasn1"
  depends_on "libtermkey"
  depends_on "libtool"
  depends_on "libunistring"
  depends_on "libusb"
  depends_on "libuv"
  depends_on "libx11"
  depends_on "libxau"
  depends_on "libxcb"
  depends_on "libxdmcp"
  depends_on "libxext"
  depends_on "libxrender"
  depends_on "libyaml"
  depends_on "lima"
  depends_on "lua"
  depends_on "luajit-openresty"
  depends_on "luv"
  depends_on "lxc"
  depends_on "lzo"
  depends_on "m4"
  depends_on "minikube"
  depends_on "mkdocs"
  depends_on "mono"
  depends_on "mpdecimal"
  depends_on "mpfr"
  depends_on "msgpack"
  depends_on "ncurses"
  depends_on "neovim"
  depends_on "neovim-qt"
  depends_on "nettle"
  depends_on "nghttp2"
  depends_on "openblas"
  depends_on "openjdk"
  depends_on "openssl@1.1"
  depends_on "p11-kit"
  depends_on "packer"
  depends_on "pcre"
  depends_on "pcre2"
  depends_on "perl"
  depends_on "pixman"
  depends_on "pkg-config"
  depends_on "pyenv"
  depends_on "python@3.10"
  depends_on "python@3.9"
  depends_on "qemu"
  depends_on "qpdf"
  depends_on "qt@5"
  depends_on "r"
  depends_on "radare2"
  depends_on "readline"
  depends_on "repo"
  depends_on "ruby"
  depends_on "rust"
  depends_on "sbt"
  depends_on "scala"
  depends_on "six"
  depends_on "snappy"
  depends_on "sqlite"
  depends_on "tcl-tk"
  depends_on "terminal-notifier"
  depends_on "tig"
  depends_on "tree"
  depends_on "tree-sitter"
  depends_on "unbound"
  depends_on "unibilium"
  depends_on "vde"
  depends_on "vim"
  depends_on "wget"
  depends_on "x86_64-elf-binutils"
  depends_on "xorgproto"
  depends_on "xz"
  depends_on "youtube-dl"
  depends_on "zstd"
  depends_on "android-sdk"
  depends_on "android-studio"
  depends_on "audacity"
  depends_on "blender"
  depends_on "brave-browser"
  depends_on "chromedriver"
  depends_on "chromium"
  depends_on "cyberduck"
  depends_on "db-browser-for-sqlite"
  depends_on "drawio"
  depends_on "firefox"
  depends_on "inkscape"
  depends_on "intellij-idea-ce"
  depends_on "iterm2"
  depends_on "karabiner-elements"
  depends_on "librecad"
  depends_on "libreoffice"
  depends_on "libreoffice-language-pack"
  depends_on "lulu"
  depends_on "openscad"
  depends_on "r"
  depends_on "unetbootin"
  depends_on "vagrant"
  depends_on "virtualbox"
  depends_on "visual-studio-code"
  depends_on "vlc"
  depends_on "vmware-fusion"
  depends_on "vnc-viewer"
  depends_on "wireshark"
  depends_on "wkhtmltopdf"
  depends_on "xquartz"
  depends_on "zotero"

  def install
    bin.install "dotfiles"
  end
end
